# -*- coding: utf-8 -*-
"""firstdatavisproject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aZ0EnMgTGDMNzmO3KF4yyWG0xJpwHdfO
"""

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from pandas.api.types import CategoricalDtype
import csv

airbnb=pd.read_csv('/content/AB_NYC_2019.csv')

sns.set(rc={"figure.figsize":(8,8)})

airbnb.head(5)

airbnb.info()

airbnb.columns

airbnb["neighbourhood_group"].unique()

airbnb['neighbourhood'].unique()

airbnb['room_type'].unique()

airbnb["neighbourhood_group"].value_counts()

airbnb[["neighbourhood_group"]].head()

airbnb["neighbourhood_group"].value_counts().plot.barh().set_title("Locations of Neighbourhood Group")

airbnb['neighbourhood_group'].value_counts().plot.bar().set_title("Locations of Neighbourhood Group")

airbnb['neighbourhood_group'].index

sns.barplot(x="neighbourhood_group",y=airbnb['neighbourhood_group'].index,data=airbnb,color='yellow').set_title("Neighbourhood Group Density")

sns.barplot(x='neighbourhood_group',y='price',hue="room_type",data=airbnb)
plt.title("Neighbourhood Group - Price - Room Type")

sns.barplot(x="price",y="room_type",hue="neighbourhood_group",data=airbnb)
plt.title("Neighbourhood Group - Price - Room Type")

sns.barplot(x="room_type",y="price",hue="host_name",data=airbnb)
#this is not useful
#It took lots of time and I stopped the execution. That's why the error.

airbnb.groupby("room_type").sum().plot.pie(y="price", autopct="%.2f%%",ylabel="",legend=False,figsize=(4,4))
plt.title("Pie Chart of Reletionship between Room Type and Price")

cols=["x","y","z"]
for col in cols:
  plt.figure(figsize=(10,10))
  sns.scatterplot(x="room_type" , y="price", data=airbnb)

sns.histplot(airbnb["price"],kde=True)

sns.histplot(airbnb["price"],kde=False)

sns.histplot(airbnb["price"],kde=True,bins=50)

sns.kdeplot(airbnb["price"])

sns.kdeplot(airbnb["price"],fill=True)

sns.jointplot(x="price",y=airbnb["host_id"],data=airbnb)

sns.catplot(x="neighbourhood_group",y="price",data=airbnb)
plt.title("Neighbourhood Group - Price")

sns.catplot(x="room_type",y="price",data=airbnb)
plt.title("Room Type - Price")

sns.catplot(x="neighbourhood_group",y="price",hue="room_type",kind="point",data=airbnb)
sns.set(rc={"figure.figsize":(6,4)})

sns.FacetGrid(airbnb, hue="room_type", height=5, xlim=(0, 10000)).map(sns.kdeplot, "host_id", fill=True).add_legend()

sns.FacetGrid(airbnb, hue="neighbourhood_group", height=5, xlim=(0, 10000)).map(sns.kdeplot, "price", fill=True).add_legend()

sns.heatmap(airbnb.corr(),annot=True)
sns.set(rc={"figure.figsize":(8,8)})
plt.title("Correlation Matrix")

sns.heatmap(airbnb.corr(),annot=False)
plt.title("Correlation Matrix")

